Repository fastcampus-final-project/fast-final-client, pull requests merged in 2024-06, with the labels that each got.

#132 feat: 홈 위젯 디자인
  app/(home)/(default-home)/@widgetSection/_components/WidgetBudget.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetCardPerformance.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetCurrentMonth.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetLastMonth.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetMyChallenge.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetMyCredit.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetSpentEveryMonth.tsx
  app/(home)/(default-home)/@widgetSection/_components/WidgetUpcomingExpenses.tsx
  app/(home)/(default-home)/@widgetSection/_components/_components/WidgetItemCardContainer.tsx
  app/(home)/(default-home)/@widgetSection/_components/_components/WidgetSkeleton.tsx
  app/(home)/(default-home)/@widgetSection/_components/index.ts
  app/(home)/(default-home)/@widgetSection/layout.tsx
  app/(home)/(default-home)/@widgetSection/loading.tsx
  app/(home)/(default-home)/@widgetSection/page.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetCurrentMonth.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetMtCredit.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetMyChallenge.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/(default-home)/loading.tsx
  app/(home)/(default-home)/page.tsx
  app/(home)/bucket-detail/layout.tsx
  app/(home)/bucket-detail/page.tsx
  app/(home)/edit-widget/_components/DragContainer.tsx
  app/(home)/edit-widget/_components/LoadingGrid.tsx
  app/(home)/edit-widget/layout.tsx
  app/api/widget/route.ts
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/_components/swiper-card-list/AssetGraphCard.tsx
  app/asset-management/_components/swiper-card-list/IncreaseMyAssetCard.tsx
  app/asset-management/_components/swiper-card-list/Ranking.tsx
  app/asset-management/layout.tsx
  app/create-bucket/_components/BucketFlowHeader.tsx
  app/create-bucket/_components/BucketStepForm.tsx
  app/create-bucket/_components/ImageComponent.tsx
  app/create-bucket/_components/NextButton.tsx
  app/create-bucket/_components/PorkoImage.tsx
  app/create-bucket/_components/step/StepFour.tsx
  app/create-bucket/_components/step/StepOne.tsx
  app/create-bucket/_components/step/StepThree.tsx
  app/create-bucket/_components/step/StepTwo.tsx
  app/create-bucket/_components/step/index.ts
  app/create-bucket/context/createBucketContext.tsx
  app/create-bucket/hooks/useGetHref.tsx
  app/create-bucket/layout.tsx
  app/create-bucket/page.tsx
  app/create-bucket/util.ts
  components/BarChart.tsx
  components/DoughnutChart.tsx
  hooks/useIsMounted.ts
  hooks/useWindowResize.ts
  package.json
  service/api/fetchOptions.ts
  utils/graph-config/generateDataSets.ts
  utils/graph-config/index.ts
  utils/graph-config/options.ts
  yarn.lock
Labels: feat, refactor

#133 feat: budget calendar layout
  app/budget-calendar/_components/common/IconDot.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/budget-calendar/_components/shared/ConsumptionWeather.tsx
  app/budget-calendar/_components/shared/RegretSpending.tsx
  app/budget-calendar/consumption/_components/ExpenseComparison.tsx
  app/budget-calendar/consumption/_components/SpendingCategories.tsx
  app/budget-calendar/consumption/page.tsx
  components/Icon.tsx
  hooks/useDefaultParam.ts
  types/budgetCalendarType.ts
Labels: feat

#135 fix: signup hydration err
  app/auth/login/_components/LoginForm.tsx
  app/auth/signup/(step-1)/page.tsx
  app/auth/signup/_components/CheckedGender.tsx
  app/auth/signup/layout.tsx
  app/auth/signup/step-2/page.tsx
  app/auth/signup/step-3/page.tsx
Labels: fix

#143 feat: budget calendar layout
  .vscode/settings.json
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-together/SharedMembers.tsx
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/_components/shared/ConsumptionWeather.tsx
  components/Icon.tsx
  components/ui/Button.tsx
  public/icons/weather/weather-1.svg
  public/icons/weather/weather-2.svg
  public/icons/weather/weather-3.svg
  public/icons/weather/weather-4.svg
  public/icons/weather/weather-5.svg
  public/icons/weather/weather-none.svg
  service/types/budgetCalendarType.ts
  shared/utils/calendarUtils.ts
  tailwind.config.ts
Labels: feat

#149 feat: 가계부 함께보기 바텀시트
  app/(home)/(default-home)/@widgetSection/layout.tsx
  app/(home)/(default-home)/@widgetSection/page.tsx
  app/(home)/(default-home)/_components/HomeTopBannerCard.tsx
  app/(home)/(default-home)/page.tsx
  app/(home)/bucket-detail/_components/BucketBottomSheet.tsx
  app/(home)/edit-widget/_components/DragContainer.tsx
  app/(home)/edit-widget/hooks/useDrag.ts
  app/(home)/edit-widget/hooks/useInsertAndDelete.ts
  app/(home)/edit-widget/types/index.ts
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/budget-calendar/_components/common/BudgetBanner.tsx
  app/budget-calendar/_components/look-alone/ExpensListBox.tsx
  app/budget-calendar/_components/look-alone/ExpensSummary.tsx
  app/budget-calendar/_components/look-alone/ExpenseItem.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/SharedMembers.tsx
  app/budget-calendar/_components/look-together/_components/ConsumptionWeather.tsx
  app/budget-calendar/_components/look-together/_components/ReactionBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/WeatherInfoBottomSheet.tsx
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/_components/shared/ConsumptionWeather.tsx
  components/BottomSheet.tsx
  package.json
  public/icons/profile/reaction-profile.svg
  service/api/home/index.ts
  shared/types/widgetDataType.ts
  tailwind.config.ts
  yarn.lock
Labels: feat

#154 feat: 로그인
  app/auth/login/_components/LoginForm.tsx
  app/auth/signup/(step-1)/StepOne.tsx
  app/budget-calendar/[viewmode]/page.tsx
  auth/authConfig.ts
  service/api/auth/index.ts
  service/api/fetchOptions.ts
  shared/actions/auth.ts
  shared/types/response/auth.ts
Labels: feat

#159 feat:
  app/(home)/(default-home)/@widgetSection/default.tsx
  app/(home)/(default-home)/@widgetSection/page.tsx
  app/(home)/(default-home)/_components/DefaultBucketListCard.tsx
  app/(home)/(default-home)/_components/HomeTopBannerCard.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/(default-home)/loading.tsx
  app/(home)/(default-home)/page.tsx
  app/(home)/edit-widget/_components/DragContainer.tsx
  app/(home)/edit-widget/_components/FixedBottom.tsx
  app/(home)/edit-widget/hooks/useDrag.ts
  app/(home)/edit-widget/hooks/useInsertAndDelete.ts
  app/(home)/edit-widget/layout.tsx
  app/(home)/edit-widget/types/index.ts
  app/[...not-found]/page.tsx
  app/api/revalidate/route.ts
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/loading.tsx
  app/asset-management/page.tsx
  app/auth/login/_components/LoginForm.tsx
  app/auth/login/layout.tsx
  app/auth/signup/(step-1)/StepOne.tsx
  app/bucket-landing/_components/BucketLanding.tsx
  app/bucket-landing/layout.tsx
  app/budget-calendar/_components/shared/RegretSpending.tsx
  app/budget-calendar/consumption/_components/SpendingCategories.tsx
  app/budget-calendar/layout.tsx
  app/budget-calendar/loading.tsx
  app/budget-calendar/page.tsx
  app/font.ts
  auth/authConfig.ts
  components/TransitonContainer.tsx
  public/images/create-bucket/bubble.webp
  public/images/not-found.png
  service/api/fetchOptions.ts
  service/api/home/action.ts
  service/api/home/index.ts
  shared/actions/auth.ts
  shared/hooks/useUserSession.ts
  shared/types/response/widgetResponse.ts
  shared/types/widgetDataType.ts
Labels: feat

#160 refactor: 로딩 root에서 적용
  app/(home)/(default-home)/loading.tsx
  app/asset-management/loading.tsx
  app/budget-calendar/[viewmode]/page.tsx
  app/create-bucket/loading.tsx
  app/financial-product/comparison/_components/CardsToCompare.tsx
  app/loading.tsx
Labels: refactor

#161 feat: budget calendar 데이터 정리
  app/budget-calendar/_components/common/BudgetBanner.tsx
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/utils/calendarUtils.ts
  app/budget-calendar/utils/mergeData.ts
  shared/types/budgetCalendarType.ts
  tailwind.config.ts
Labels: feat

#164 refactor: 캘린더 함께 보기 수정
  app/(home)/(default-home)/@widgetSection/_components/WidgetCurrentMonth.tsx
  app/(home)/(default-home)/_components/DefaultBucketListCard.tsx
  app/(home)/(default-home)/_components/HomeTopBannerCard.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/(default-home)/page.tsx
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/_components/ReactionBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/_components/shared/RegretSpending.tsx
  app/layout.tsx
  auth/authConfig.ts
  components/Navbar.tsx
  components/header/DefaultHeader.tsx
  middleware.ts
  public/icons/budget-calendar/airpodmax.webp
  public/icons/budget-calendar/airpodsMax.svg
  public/icons/budget-calendar/burger.webp
  public/icons/budget-calendar/chicken.svg
  public/icons/budget-calendar/chicken.webp
  public/icons/budget-calendar/clock.svg
  public/icons/budget-calendar/coffee.svg
  public/icons/budget-calendar/coffee.webp
  public/icons/budget-calendar/hamburger.svg
  public/icons/budget-calendar/macBook.svg
  public/icons/budget-calendar/macbook.webp
  public/icons/budget-calendar/pencil.svg
  public/icons/budget-calendar/pencil.webp
  public/icons/budget-calendar/sushi.svg
  public/icons/budget-calendar/sushi.webp
  public/icons/budget-calendar/watch.webp
  public/images/default-profile/profile_1.jpg
  public/images/default-profile/profile_2.jpg
  public/images/default-profile/profile_3.jpg
  routes.tsx
  service/constants/index.ts
  shared/hooks/useUserSession.ts
  shared/types/budgetCalendarType.ts
  shared/types/response/auth.ts
  shared/utils/dateUtils.ts
  tailwind.config.ts
Labels: feat, refactor

#165 fix: 미들웨어 경로 변경 수정
  middleware.ts
Labels: fix

#175 feat: 가계부 목표 설정 관리 플로우
  app/auth/_components/ClearInputValueIcon.tsx
  app/budget-calendar/_components/common/BottomSheetTitle.tsx
  app/budget-calendar/_components/common/TargetManagementInput.tsx
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/_components/look-alone/ManagementBottomSheet.tsx
  app/budget-calendar/_components/look-alone/TargetBudgetBottomSheet.tsx
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  app/budget-calendar/utils/mergeData.ts
  components/BottomSheet.tsx
  components/ui/Input.tsx
  shared/types/budgetCalendarType.ts
  tailwind.config.ts
Labels: feat

#178 feat: budget calendar api 혼자봐요, 공유한 멤버
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  app/budget-calendar/_components/look-together/SharedMembers.tsx
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/utils/generateMergeData.ts
  service/api/calendar/index.ts
  service/api/calendar/share.ts
  shared/types/budgetCalendarType.ts
  shared/utils/formatNumber.ts
Labels: feat

#179 feat: 알림 페이지 작성
  app/(home)/(default-home)/_components/BucketListCard.tsx
  app/(home)/(default-home)/_components/MyWallteBottomSheet.tsx
  app/(home)/bucket-detail/_components/BucketBottomSheet.tsx
  app/(home)/bucket-detail/data.ts
  app/(home)/bucket-detail/page.tsx
  app/auth/signup/_components/CheckedGender.tsx
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  app/budget-calendar/_components/look-alone/_components/ExpensDetailBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/ReactionBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  app/create-bucket/_components/step/StepTwo.tsx
  app/financial-product/_components/SpotlightCardSection.tsx
  app/financial-product/ai-recommendations/_components/PerfectFinancialProductSection.tsx
  app/financial-product/comparison/_components/ComparisonSection.tsx
  app/financial-product/comparison/select-category/result/_components/ComparisonResult.tsx
  app/globals.css
  app/notification/data.ts
  app/notification/layout.tsx
  app/notification/page.tsx
  components/BottomSheet.tsx
  components/header/DefaultHeader.tsx
  components/header/IsBackHeader.tsx
  components/ui/LoadingBackdrop.tsx
  components/ui/TextButton.tsx
  public/icons/logos/bank/bank-poko-1.svg
  public/icons/logos/bank/bank-poko-2.svg
  public/images/default-profile/profile_4.jpg
  public/images/default-profile/profile_5.jpg
  public/images/default-profile/profile_6.jpg
  routes.tsx
  shared/actions/auth.ts
  shared/utils/conversion.ts
Labels: feat, refactor

#184 feat: 함께봐요 공유한 멤버 연결
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/SharedMembers.tsx
  app/budget-calendar/_components/shared/ConsumptionWeather.tsx
  app/budget-calendar/_components/shared/RegretSpending.tsx
  service/api/budget/index.ts
  shared/types/budgetCalendarType.ts
  shared/types/response/targetBudget.ts
Labels: feat

#185 Fix/calendar date
  app/(home)/(default-home)/layout.tsx
  app/auth/login/_components/LoginForm.tsx
  app/budget-calendar/_components/look-alone/ExpensListBox.tsx
  app/layout.tsx
  next.config.mjs
  public/images/default-profile/profile_1.jpg
  public/images/default-profile/profile_1.webp
  public/images/default-profile/profile_2.jpg
  public/images/default-profile/profile_2.webp
  public/images/default-profile/profile_3.jpg
  public/images/default-profile/profile_3.webp
  public/images/default-profile/profile_4.jpg
  public/images/default-profile/profile_4.webp
  public/images/default-profile/profile_5.jpg
  public/images/default-profile/profile_5.webp
  public/images/default-profile/profile_6.jpg
  public/images/default-profile/profile_6.webp
  public/images/not-found.png
  public/vercel.svg
  service/api/auth/index.ts
  shared/utils/dateUtils.ts
  tailwind.config.ts
Labels: fix, add

#188 feat: 가계부 후회 소비 연결
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/shared/RegretSpending.tsx
  app/budget-calendar/_components/shared/resgrestData.ts
  public/icons/budget-calendar/smile.webp
  service/api/calendar/share.ts
  shared/types/response/regretSpending.ts
  store/yearMonthStore.ts
Labels: feat

#190 refactor: bottom sheet isBack 수정
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  components/BottomSheet.tsx
Labels: refactor

#191 feat: 소비분석 소비날씨, 후회 소비 user 전달 수정
  app/budget-calendar/_components/shared/RegretSpending.tsx
  app/budget-calendar/consumption/page.tsx
Labels: feat

#192 feat: 소비내역 이름 받아오기
  app/budget-calendar/consumption/_components/MonthSpending.tsx
  app/budget-calendar/consumption/_components/SpendingCategories.tsx
  app/budget-calendar/consumption/page.tsx
Labels: feat

#193 refactor: 캘린더 히스토리 api 수정
  app/(home)/(default-home)/@widgetSection/layout.tsx
  app/(home)/(default-home)/@widgetSection/page.tsx
  app/(home)/(default-home)/_components/ConsumeWeatherCard.tsx
  app/(home)/(default-home)/_components/HomeBucketBannerCard.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListFooter.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListHeader.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/bucket-detail/page.tsx
  app/api/bucket/savingbook/route.ts
  app/api/bucket/spendbook/route.ts
  app/api/signup/route.ts
  app/api/wallet/route.ts
  app/budget-calendar/_components/look-alone/ExpensListBox.tsx
  app/budget-calendar/_components/look-alone/ExpenseItem.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  components/header/DefaultHeader.tsx
  components/header/IsBackHeader.tsx
  service/api/calendar/index.ts
  shared/types/response/calendarHistroy.ts
  shared/utils/dateUtils.ts
  tailwind.config.ts
Labels: refactor

#195 refactor: 반응보기 디자인 수정 반영
  app/budget-calendar/_components/look-alone/_components/ExpensDetailBottomSheet.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/_components/ReactionBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  app/budget-calendar/_components/look-together/data.ts
  app/create-bucket/_components/step/StepFour.tsx
  app/create-bucket/data.ts
  app/notification/page.tsx
Labels: refactor

#200 style: 가계부 qa 수정
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/page.tsx
  components/ui/Tab.tsx
Labels: style

#205 refactor: widgetSection session 없을시 fetch 않게 수정
  app/(home)/(default-home)/@widgetSection/page.tsx
Labels: fix

#206 feat: 가계부 헤더 탭 고정 및 함께봐요 계속 로딩되는 부분 수정
  app/budget-calendar/(defaultHeaderLayout)/layout.tsx
  app/budget-calendar/(defaultHeaderLayout)/page.tsx
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  components/ui/Tab.tsx
Labels: fix, feat

#207 refactor: 캘린더 함께보기 api 연결
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/_components/ReactionBottomSheet.tsx
  app/budget-calendar/_components/look-together/_components/SubmitEmojiBottomSheet.tsx
  app/budget-calendar/_components/look-together/data.ts
  app/budget-calendar/_components/shared/Calendar.tsx
  app/budget-calendar/context/SubmitEmojiProvider.tsx
  app/budget-calendar/hooks/useAddOrRemoveEmojiHooks.ts
  app/budget-calendar/utils/generateMergeData.ts
  shared/types/budgetCalendarType.ts
Labels: refactor

#216 feat: 목표 예산 설정 수정 관리
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/_components/look-alone/ManagementBottomSheet.tsx
  app/budget-calendar/_components/look-alone/TargetBudgetBottomSheet.tsx
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  components/header/DefaultHeader.tsx
  service/api/calendar/index.ts
  shared/types/budgetCalendarType.ts
  shared/types/response/targetBudget.ts
Labels: feat

#219 fix: iphone 오류 수정
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
Labels: fix

#224 feat: 데이터 변경에 따라 react-query 캐싱 지우기
  app/budget-calendar/_components/look-alone/ExpenseItem.tsx
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/_components/look-alone/TargetBudgetBottomSheet.tsx
  app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
  app/budget-calendar/_components/shared/YearMonthDropdown.tsx
Labels: feat
