Repository fastcampus-final-project/fast-final-client, pull requests merged in 2024-05, with the labels that each got.

#17 feat: 홈화면 레이아웃, 드래그,uuid 패키지 설치
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/DraggableCardContainer.tsx
  app/(home)/_components/DraggableCardItem.tsx
  app/(home)/page.tsx
  components/ui/card/Card.tsx
  components/ui/card/CardContent.tsx
  components/ui/card/CardFooter.tsx
  components/ui/card/CardHeader.tsx
  components/ui/card/index.ts
  package-lock.json
  package.json
  public/images/home-bucket-rabbit.png
Labels: feat

#19 feat: 회원가입 - 주소선택, 약관동의 작성
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/DraggableCardContainer.tsx
  app/(home)/page.tsx
  app/auth/signup/_components/SignupForm.tsx
  app/auth/signup/_components/step-form/StepFiveForm.tsx
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/auth/signup/_components/step-form/StepOneForm.tsx
  app/auth/signup/_components/step-form/StepTwoForm.tsx
  app/auth/signup/_components/step-form/_components/ArrowRightIcon.tsx
  app/auth/signup/_components/step-form/_components/CheckIcon.tsx
  app/auth/signup/_components/step-form/_components/CheckedGender.tsx
  app/auth/signup/_components/step-form/_components/DaumAddress.tsx
  app/auth/signup/_components/step-form/index.ts
  app/auth/signup/page.tsx
  app/globals.css
  components/ui/Text.tsx
  components/ui/card/Card.tsx
  components/ui/card/CardContent.tsx
  components/ui/card/index.ts
  hooks/useFunnel.tsx
  hooks/useHooks.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/noEmptyArray.ts
  types/svgComponentProps.ts
  types/type.ts
  utils/twMerge.ts
Labels: feat

#25 feat: 자산관리 구조 작업
  app/asset-management/_components/NetWorth.tsx
  app/asset-management/page.tsx
  app/globals.css
  app/layout.tsx
  tailwind.config.ts
Labels: feat, refactor

#26 feat: input component의 props에 fontSize 누락수정
  components/ui/Input.tsx
Labels: feat

#28 feat: 홈 버킷,챌린지 카드 컴포넌트
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/ConsumeWeatherCard.tsx
  app/(home)/_components/DraggableCardContainer.tsx
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/ProgressBar.tsx
  app/(home)/_components/TextBubble.tsx
  app/(home)/page.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/SectionTitle.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/layout.tsx
  components/ui/Text.tsx
  tailwind.config.ts
Labels: feat, refactor

#29 feat: 홈 레이아웃 작성
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-list/BucketListContent.tsx
  app/(home)/_components/bucket-list/BucketListFooter.tsx
  app/(home)/_components/bucket-list/BucketListHeader.tsx
  app/(home)/_components/bucket-list/ProgressBar.tsx
  app/(home)/_components/bucket-list/TextBubble.tsx
  app/(home)/_components/bucket-list/index.ts
  app/(home)/_components/home-widget/WidgetItem.tsx
  app/(home)/page.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  components/SectionTitle.tsx
Labels: feat

#31 feat: tailwind config 추가
  app/layout.tsx
  components/icons/ArrowLeftIcon.tsx
  components/icons/index.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feat

#33 feat: input checkbox 컴포넌트 생성
  app/budget-calendar/page.tsx
  app/layout.tsx
  components/ui/CheckBox.tsx
  public/images/checkbox-green.svg
  public/images/checkbox-off.svg
  public/images/checkbox-on.svg
Labels: feat

#36 refactor: 회원가입 4,5 레이아웃 수정
  app/auth/signup/_components/step-form/StepFiveForm.tsx
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/auth/signup/_components/step-form/_components/CheckedGender.tsx
  app/auth/signup/layout.tsx
  components/icons/weather/WeatherFive.tsx
  components/icons/weather/WeatherOne.tsx
  components/icons/weather/WeatherThree.tsx
  components/icons/weather/WeatherTwo.tsx
  components/icons/weather/WeatherZero.tsx
Labels: refactor

#41 feat: 홈 위젯 영역 작성중
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/ConsumeWeatherSesction.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-list/BucketListHeader.tsx
  app/(home)/_components/bucket-list/TextBubble.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/(home)/_components/home-widget/IsEditWidgetContainer.tsx
  app/(home)/_components/home-widget/IsEditWidgetItem.tsx
  app/(home)/_components/home-widget/WidgetItem.tsx
  app/(home)/page.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/page.tsx
  app/globals.css
  app/layout.tsx
  components/Header.tsx
  components/MotionCarousel.tsx
  components/SectionTitle.tsx
  components/icons/MenuBarThreeIcon.tsx
  components/icons/MinusIcon.tsx
  components/icons/PlusIcon.tsx
  components/icons/arrow/ArrowBackIcon.tsx
  components/ui/Button.tsx
  components/ui/card/Card.tsx
  hooks/useIsMounted.ts
  utils/debounce.ts
  utils/util.ts
Labels: feat

#43 feat: switch component 생성
  app/budget-calendar/page.tsx
  components/ui/CheckBox.tsx
  components/ui/Switch.tsx
  tailwind.config.ts
Labels: feat

#44 feat: 회원가입 스텝 통합
  app/auth/signup/_components/PwInput.tsx
  app/auth/signup/_components/SignupForm.tsx
  app/auth/signup/_components/SignupNav.tsx
  app/auth/signup/_components/step-form/StepOneForm.tsx
  app/auth/signup/_components/step-form/StepThreeForm.tsx
  app/auth/signup/_components/step-form/StepTwoForm.tsx
Labels: feat

#45 feat: 바텀 네비 작성, 아이콘 추가
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/home-widget/IsEditWidgetContainer.tsx
  app/auth/signup/_components/SignupNav.tsx
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/financial-product/comparison/page.tsx
  app/layout.tsx
  components/Header.tsx
  components/Navbar.tsx
  components/icons/arrow/ArrowBackIcon.tsx
  components/icons/arrow/ArrowLeftIcon.tsx
  components/icons/arrow/ArrowRightIcon.tsx
  components/icons/arrow/ArrowUpFillIcon.tsx
  components/icons/bottom-nav/AssetManagementIcon.tsx
  components/icons/bottom-nav/BudgetCalendarIcon.tsx
  components/icons/bottom-nav/FinancialProductIcon.tsx
  components/icons/bottom-nav/HomeIcon.tsx
  components/icons/bottom-nav/NavAllIcon.tsx
  components/icons/index.ts
  components/ui/Button.tsx
Labels: feat

#48 feat: 홈 배너 추가
  app/(home)/_components/HomeBanner.tsx
  components/MotionCarousel.tsx
  components/icons/banner/CardEventIcon.tsx
  components/icons/banner/SavingEventIcon.tsx
  components/icons/banner/TodayBenefitIcon.tsx
  components/icons/index.ts
Labels: feat

#50 refactor: 자산관리 순자산영역 드래그 재작성
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/(home)/page.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/layout.tsx
  app/asset-management/page.tsx
  app/edit-widget/_components/FixedBottom.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  app/edit-widget/page.tsx
  components/Header.tsx
  components/MotionCarousel.tsx
  components/Navbar.tsx
  components/SectionTitle.tsx
  components/icons/BusIcon.tsx
  components/icons/CheckIcon.tsx
  components/icons/CreditCardIcon.tsx
  components/icons/MenuBarThreeIcon.tsx
  components/icons/MinusIcon.tsx
  components/icons/MonthlyRentIcon.tsx
  components/icons/PlusIcon.tsx
  components/icons/SearchIcon.tsx
  components/icons/SubsServiceIcon.tsx
  components/icons/banner/SavingEventIcon.tsx
  components/icons/bottom-nav/BottomNavIcon.tsx
  hooks/useWindowResize.ts
Labels: feat, refactor

#53 refactor: 헤더,바텀 아이콘 수정
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/(home)/layout.tsx
  app/asset-management/layout.tsx
  app/edit-widget/page.tsx
  components/Header.tsx
  components/Navbar.tsx
  components/header/DefaultHeader.tsx
  components/header/IsBackHeader.tsx
  components/header/index.ts
  components/icons/bottom-nav/BottomNavIcon.tsx
  package-lock.json
  routes.tsx
  yarn.lock
Labels: refactor

#56 refactor: 인풋 디자인 수정 & svg 이미지 교체
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/budget-calendar/page.tsx
  components/header/DefaultHeader.tsx
  components/header/IsBackHeader.tsx
  components/icons/BusIcon.tsx
  components/icons/DeleteIcon.tsx
  components/icons/KbCardIcon.tsx
  components/icons/MonthlyRentIcon.tsx
  components/icons/NotiIcon.tsx
  components/icons/ProfileIcon.tsx
  components/icons/ShinaHanCardIcon.tsx
  components/icons/SubsServiceIcon.tsx
  components/icons/arrow/ArrowIcon.tsx
  components/icons/banner/CardEventIcon.tsx
  components/icons/banner/SavingEventIcon.tsx
  components/icons/banner/TodayBenefitIcon.tsx
  components/icons/index.ts
  components/icons/signup/InvisibleIcon.tsx
  components/icons/signup/VisibleIcon.tsx
  components/icons/weather/WeatherIcon.tsx
  components/ui/Input.tsx
  public/images/arrow/arrow-down.svg
  public/images/arrow/arrow-left.svg
  public/images/arrow/arrow-next.svg
  public/images/arrow/arrow-prev.svg
  public/images/arrow/arrow-right.svg
  public/images/arrow/arrow-up.svg
  public/images/arrow/bxs-up-arrow.svg
  public/images/asset/asset-card.svg
  public/images/asset/bus.svg
  public/images/asset/home-rental.svg
  public/images/asset/kb-card.svg
  public/images/asset/male.svg
  public/images/asset/ott.svg
  public/images/asset/shinhan-card.svg
  public/images/banner/banner-card-event.svg
  public/images/banner/banner-saving-event.svg
  public/images/banner/banner-today-benefits.svg
  public/images/header/header-alarm-on.svg
  public/images/header/header-alarm.svg
  public/images/header/header-profile.svg
  public/images/weather/weather-1.svg
  public/images/weather/weather-2.svg
  public/images/weather/weather-3.svg
  public/images/weather/weather-4.svg
  public/images/weather/weather-5.svg
Labels: refactor, add

#59 refactor: 홈 -> 버킷,챌린지 섹션 수정, 로고 수정, AI 맞춤영역 수정
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/ChallengeCard.tsx
  app/(home)/_components/ConsumeWeatherSesction.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-challenge/ListCard.tsx
  app/(home)/_components/bucket-challenge/ListContent.tsx
  app/(home)/_components/bucket-challenge/ListFooter.tsx
  app/(home)/_components/bucket-challenge/ListHeader.tsx
  app/(home)/_components/bucket-challenge/TextBubble.tsx
  app/(home)/_components/bucket-challenge/index.ts
  app/(home)/_components/bucket-list/BucketListContent.tsx
  app/(home)/_components/bucket-list/TextBubble.tsx
  app/(home)/_components/bucket-list/index.ts
  app/(home)/page.tsx
  app/financial-product/page.tsx
  components/MotionCarousel.tsx
  components/header/DefaultHeader.tsx
  public/images/home-bucket-rabbit.png
  public/images/home/bucket_img_step1.svg
  public/images/home/bucket_img_stpe3.svg
  public/images/home/butket_img_step2.svg
  public/images/home/challenge_img.svg
  public/images/home/home_ai.svg
  public/images/logo.svg
  tailwind.config.ts
Labels: refactor

#60 fix: 드래그 할때 이미지 선택 방지
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/ChallengeCard.tsx
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/financial-product/page.tsx
Labels: fix

#63 refactor: 아이콘 경로 수정
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/page.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/auth/signup/_components/step-form/StepFiveForm.tsx
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/budget-calendar/page.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  app/edit-widget/_components/MenuBarThreeIcon.tsx
  app/edit-widget/_components/MinusIcon.tsx
  app/edit-widget/_components/PlusIcon.tsx
  components/BottomNavIcon.tsx
  components/Navbar.tsx
  components/header/DefaultHeader.tsx
  components/header/IsBackHeader.tsx
  components/icons/index.ts
  components/icons/widget/Budget.tsx
  components/icons/widget/Netflix.tsx
  components/ui/Input.tsx
  public/icons/product/카테고리=온라인.svg
  public/icons/product/카테고리=주유.svg
  public/icons/product/카테고리=카페.svg
  public/icons/product/카테고리=통신비.svg
Labels: refactor

#66 fix: 뒤로가기 헤더 아이콘경로 수정, 홈 날씨이미지 경로 수정
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  components/header/IsBackHeader.tsx
Labels: fix

#68 chore: img 이름 변경
  public/icons/logos/bank/bank-ibk.svg
  public/icons/logos/bank/bank-kakao.svg
  public/icons/logos/bank/bank-kb.svg
  public/icons/logos/bank/bank-nh.svg
  public/icons/logos/bank/bank-shinhan.svg
  public/icons/logos/bank/bank-toss.svg
  public/icons/logos/bank/bank-woori.svg
  public/icons/logos/card/card-bc.svg
  public/icons/logos/card/card-hyundai.svg
  public/icons/logos/card/card-kakao.svg
  public/icons/logos/card/card-shinhan.svg
  public/icons/product/product-cafe.svg
  public/icons/product/product-communication.svg
  public/icons/product/product-culture.svg
  public/icons/product/product-cvs.svg
  public/icons/product/product-mart.svg
  public/icons/product/product-oiling.svg
  public/icons/product/product-online.svg
  public/icons/product/product-shopping.svg
  public/icons/product/product-stores.svg
  public/icons/product/product-subscribe.svg
  public/icons/product/product-traffic.svg
  public/icons/product/product-travel.svg
  public/icons/system-icon/filter.svg
  public/icons/system-icon/heart.svg
  public/icons/system-icon/info.svg
  public/icons/system-icon/search.svg
  public/icons/system-icon/setting.svg
  public/icons/system-icon/system/card-bus.svg
  public/icons/system-icon/system/card-cafe.svg
  public/icons/system-icon/system/card-cvs.svg
  public/icons/system-icon/system/card-delivery.svg
  public/icons/system-icon/system/card-food.svg
  public/icons/system-icon/system/card-online.svg
  public/icons/system-icon/system/card-pay.svg
  public/icons/system-icon/system/card-performance.svg
  public/icons/system-icon/system/card-point.svg
  public/icons/system-icon/system/card-streaming.svg
  public/icons/system-icon/system/card-taxi.svg
Labels: chore

#69 feat: 홈 위젯 편집영역 드래그
  app/(home)/_components/DraggableCardContainer.tsx
  app/(home)/_components/DraggableCardItem.tsx
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-challenge/ListContent.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/edit-widget/_components/DragOverWidget.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  app/edit-widget/_components/MenuBarThreeIcon.tsx
  app/edit-widget/_components/MinusIcon.tsx
  app/edit-widget/_components/PlusIcon.tsx
  app/edit-widget/hooks/useDrag.ts
  app/edit-widget/hooks/useInsertAndDelete.ts
  app/edit-widget/page.tsx
  app/globals.css
  components/Icon.tsx
  components/MotionCarousel.tsx
  components/header/DefaultHeader.tsx
  public/font/LICENSE
  public/font/SUIT-Bold.woff2
  public/font/SUIT-ExtraBold.woff2
  public/font/SUIT-ExtraLight.woff2
  public/font/SUIT-Heavy.woff2
  public/font/SUIT-Light.woff2
  public/font/SUIT-Medium.woff2
  public/font/SUIT-Regular.woff2
  public/font/SUIT-SemiBold.woff2
  public/font/SUIT-Thin.woff2
  public/icons/asset-page/three-bar.svg
  public/icons/asset-page/widget-minus.svg
  types/widget-type/widgetType.ts
Labels: feat

#71 refactor: 홈 레이아웃 순서 변경
  app/(home)/_components/ConsumeWeatherCard.tsx
  app/(home)/_components/ConsumeWeatherSesction.tsx
  app/(home)/_components/HomeAiBannerCard.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-challenge/ListCard.tsx
  app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
  app/(home)/page.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/edit-widget/page.tsx
  components/Icon.tsx
  components/ProgressBar.tsx
  components/header/IsBackHeader.tsx
  public/images/home/ai-banner.svg
Labels: refactor

#73 refactor: 드래그 카드 선택시 크기 변경 애니메이션 추가
  app/auth/signup/_components/SignupForm.tsx
  app/budget-calendar/page.tsx
  app/edit-widget/_components/DragOverWidget.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  app/edit-widget/hooks/useDrag.ts
  app/edit-widget/page.tsx
  components/Icon.tsx
  tailwind.config.ts
Labels: refactor

#75 refactor: 회원가입 페이지 디자인 적용
  app/auth/signup/_components/SignupForm.tsx
  app/auth/signup/_components/SignupHeader.tsx
  app/auth/signup/_components/step-form/StepFiveForm.tsx
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/auth/signup/_components/step-form/StepOneForm.tsx
  app/auth/signup/_components/step-form/StepThreeForm.tsx
  app/auth/signup/_components/step-form/StepTwoForm.tsx
  app/auth/signup/_components/step-form/_components/CheckedGender.tsx
  app/auth/signup/_components/step-form/_components/DaumAddress.tsx
  app/auth/signup/_components/step-form/index.ts
  app/auth/signup/layout.tsx
  app/edit-widget/_components/FixedBottom.tsx
  app/globals.css
  components/header/IsBackHeader.tsx
  components/ui/CheckBox.tsx
  hooks/useFunnel.tsx
  public/icons/system-icon/checkbox/checkbox-off.svg
  public/icons/system-icon/checkbox/checkbox-on.svg
  public/icons/system-icon/checkbox/round-checkbox-green.svg
  public/icons/system-icon/checkbox/round-checkbox-off.svg
  public/icons/system-icon/checkbox/round-checkbox-on.svg
Labels: refactor

#80 refactor: 회원가입 이메일, 패스워드 검증 로직
  app/api/signup/route.ts
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/MyCreditSection.tsx
  app/auth/signup/(step-1)/page.tsx
  app/auth/signup/_components/CheckedGender.tsx
  app/auth/signup/_components/CodeInput.tsx
  app/auth/signup/_components/DaumAddress.tsx
  app/auth/signup/_components/EmailInput.tsx
  app/auth/signup/_components/IdInput.tsx
  app/auth/signup/_components/InputLayout.tsx
  app/auth/signup/_components/NameInput.tsx
  app/auth/signup/_components/PhoneInput.tsx
  app/auth/signup/_components/PwInput.tsx
  app/auth/signup/_components/ReconfirmPwInput.tsx
  app/auth/signup/_components/SignupForm.tsx
  app/auth/signup/_components/SignupFormProvider.tsx
  app/auth/signup/_components/SignupHeader.tsx
  app/auth/signup/_components/SignupNav.tsx
  app/auth/signup/_components/signupSchema.ts
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/auth/signup/_components/step-form/StepOneForm.tsx
  app/auth/signup/_components/step-form/StepThreeForm.tsx
  app/auth/signup/_components/step-form/StepTwoForm.tsx
  app/auth/signup/layout.tsx
  app/auth/signup/page.tsx
  app/auth/signup/step-2/page.tsx
  app/auth/signup/step-3/page.tsx
  app/budget-calendar/page.tsx
  components.json
  components/Spinner.tsx
  components/ui/Button.tsx
  components/ui/CheckBox.tsx
  components/ui/form.tsx
  components/ui/label.tsx
  package.json
  public/images/asset-page/bank-book.svg
  public/images/asset-page/hand.svg
  service/api/auth/index.ts
  service/api/fetchOptions.ts
  service/constants/index.ts
  yarn.lock
Labels: chore, refactor

#81 feat: budget calendar layout
  app/budget-calendar/_components/common/BudgetBanner.tsx
  app/budget-calendar/_components/common/Line.tsx
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-alone/ExpensListBox.tsx
  app/budget-calendar/_components/look-alone/ExpenseItem.tsx
  app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/budget-calendar/page.tsx
  components/ui/Tab.tsx
  public/icons/budget-calendar/airpodsMax.svg
  public/icons/budget-calendar/chicken.svg
  public/icons/budget-calendar/clock.svg
  public/icons/budget-calendar/coffee.svg
  public/icons/budget-calendar/hamburger.svg
  public/icons/budget-calendar/macBook.svg
  public/icons/budget-calendar/pencil.svg
  public/icons/budget-calendar/small-pig.svg
  public/icons/budget-calendar/sushi.svg
  public/icons/categories/background/categories-1.svg
  public/icons/categories/background/categories-10.svg
  public/icons/categories/background/categories-11.svg
  public/icons/categories/background/categories-12.svg
  public/icons/categories/background/categories-13.svg
  public/icons/categories/background/categories-14.svg
  public/icons/categories/background/categories-2.svg
  public/icons/categories/background/categories-3.svg
  public/icons/categories/background/categories-4.svg
  public/icons/categories/background/categories-5.svg
  public/icons/categories/background/categories-6.svg
  public/icons/categories/background/categories-7.svg
  public/icons/categories/background/categories-8.svg
  public/icons/categories/background/categories-9.svg
  public/icons/categories/background/categories-regret.svg
  public/icons/system-icon/arrow/arrow-right-gray.svg
  public/icons/system-icon/plus-gray.svg
  tailwind.config.ts
  types/budgetCalendarType.ts
Labels: feat

#82 refactor: step-3 검증 작성
  app/(home)/_components/HomeWidgetSection.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/auth/signup/_components/CheckedGender.tsx
  app/auth/signup/step-3/page.tsx
  app/auth/signup/step-4/page.tsx
  components/ui/Button.tsx
  public/icons/system-icon/search-2.svg
Labels: refactor

#85 fix: build error
  app/auth/signup/_components/step-form/index.ts
  components/ui/TextButton.tsx
Labels: fix

#90 fix: env
  app/not-found.tsx
  service/api/fetchOptions.ts
Labels: fix

#102 refactor: 회원가입 폼 수정
  app/(home)/_components/HomeAiBannerCard.tsx
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/bucket-challenge/ListFooter.tsx
  app/(home)/_components/bucket-challenge/ListHeader.tsx
  app/(home)/_components/bucket-challenge/TextBubble.tsx
  app/asset-management/_components/CollectAssetSection.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/auth/login/page.tsx
  app/auth/signup/(step-1)/page.tsx
  app/auth/signup/_components/ClearInputValueIcon.tsx
  app/auth/signup/_components/SignupFormProvider.tsx
  app/auth/signup/_components/SignupHeader.tsx
  app/auth/signup/_components/signupSchema.ts
  app/auth/signup/_components/step-form/StepFourForm.tsx
  app/auth/signup/_components/step-form/StepOneForm.tsx
  app/auth/signup/_components/step-form/StepThreeForm.tsx
  app/auth/signup/_components/step-form/StepTwoForm.tsx
  app/auth/signup/_components/step-form/index.ts
  app/auth/signup/step-2/page.tsx
  app/auth/signup/step-3/page.tsx
  app/auth/signup/step-4/page.tsx
  app/edit-widget/_components/DragContainer.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  app/edit-widget/_components/LoadingGrid.tsx
  app/edit-widget/_components/TopContents.tsx
  app/edit-widget/page.tsx
  app/font.ts
  app/globals.css
  app/layout.tsx
  components.json
  components/Skeleton.tsx
  components/ui/Input.tsx
  components/ui/Text.tsx
  hooks/useFunnel.tsx
  hooks/useTotalWidth.ts
  package.json
  public/font/SUIT-ExtraLight.woff2
  public/font/SUIT-Heavy.woff2
  public/font/SUIT-Light.woff2
  public/font/SUIT-Thin.woff2
  public/icons/asset-page/ico_plus.svg
  public/icons/signup/delete.svg
  public/icons/signup/eye-hide.svg
  public/icons/signup/eye-slash.svg
  public/icons/signup/eye.svg
  tailwind.config.ts
  yarn.lock
Labels: refactor

#104 feat: 로그인 폼 작성
  app/auth/_components/AuthHeader.tsx
  app/auth/_components/ClearInputValueIcon.tsx
  app/auth/_components/EyeIcon.tsx
  app/auth/login/_components/LoginForm.tsx
  app/auth/login/layout.tsx
  app/auth/login/page.tsx
  app/auth/schema/loginSchema.ts
  app/auth/schema/signupSchema.ts
  app/auth/signup/(step-1)/page.tsx
  app/auth/signup/_components/CheckedGender.tsx
  app/auth/signup/_components/ClearInputValueIcon.tsx
  app/auth/signup/_components/DaumAddress.tsx
  app/auth/signup/_components/SignupFormProvider.tsx
  app/auth/signup/step-2/page.tsx
  app/auth/signup/step-3/page.tsx
  app/auth/signup/step-4/page.tsx
  app/edit-widget/_components/IsEditWidgetItem.tsx
  components/ui/TextButton.tsx
Labels: feat, refactor

#108 feat: 홈 내계좌 바텀시트
  actions/serverAction.ts
  app/(home)/_components/BucketListCard.tsx
  app/(home)/_components/ChallengeCard.tsx
  app/(home)/_components/HomeAiBannerCard.tsx
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/HomeWidgetSection.tsx
  app/(home)/_components/MyWalletButton.tsx
  app/(home)/_components/MyWallteBottomSheet.tsx
  app/(home)/_components/WidgetSkeleton.tsx
  app/(home)/context/OpenWalletProvider.tsx
  app/(home)/layout.tsx
  app/(home)/loading.tsx
  app/(home)/page.tsx
  app/api/wallet/route.ts
  app/api/widget/route.ts
  app/asset-management/_components/MyCreditSection.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/asset-management/layout.tsx
  app/asset-management/page.tsx
  app/edit-widget/_components/DragContainer.tsx
  app/edit-widget/_components/LoadingGrid.tsx
  app/edit-widget/_components/TopContents.tsx
  app/edit-widget/page.tsx
  app/layout.tsx
  components/BottomSheet.tsx
  components/Icon.tsx
  components/Skeleton.tsx
  components/header/DefaultHeader.tsx
  components/ui/skeleton/CardSkeleton.tsx
  components/ui/skeleton/SqureSkeleton.tsx
  components/ui/skeleton/index.ts
  public/icons/asset-page/bus.svg
  public/icons/asset-page/month-rental.svg
  public/icons/asset-page/subs.svg
  public/icons/home/wallet.svg
  public/images/home/Frame-1707485091.webp
  public/images/home/ai-banner.svg
  public/images/home/ai-banner.webp
  public/images/home/bucket_img_step1.webp
  public/images/home/butket_img_step2.svg
  public/images/home/butket_img_step2.webp
  public/images/home/challenge_img.svg
  public/images/home/challenge_img.webp
  service/api/home/index.ts
Labels: feat, refactor

#110 refactor: MotionCarouse -> SwiperWapper로 교체
  app/(home)/_components/HomeBanner.tsx
  app/(home)/_components/MyWalletButton.tsx
  app/(home)/_components/MyWallteBottomSheet.tsx
  app/(home)/page.tsx
  app/asset-management/_components/MyAssetsGraphSection.tsx
  app/edit-widget/layout.tsx
  components/BottomSheet.tsx
  components/MotionCarousel.tsx
  components/SwiperWrapper.tsx
  service/api/home/index.ts
Labels: refactor

#111 feat: 홈 버킷리스트 확인 페이지 작성
  app/(home)/(default-home)/_components/BucketListCard.tsx
  app/(home)/(default-home)/_components/ChallengeCard.tsx
  app/(home)/(default-home)/_components/ConsumeWeatherCard.tsx
  app/(home)/(default-home)/_components/DefaultBucketListCard.tsx
  app/(home)/(default-home)/_components/HomeAiBannerCard.tsx
  app/(home)/(default-home)/_components/HomeBanner.tsx
  app/(home)/(default-home)/_components/HomeWidgetSection.tsx
  app/(home)/(default-home)/_components/MyWalletButton.tsx
  app/(home)/(default-home)/_components/MyWallteBottomSheet.tsx
  app/(home)/(default-home)/_components/WidgetSkeleton.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListCard.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListContent.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListFooter.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListHeader.tsx
  app/(home)/(default-home)/_components/bucket-challenge/TextBubble.tsx
  app/(home)/(default-home)/_components/bucket-challenge/index.ts
  app/(home)/(default-home)/_components/widget-item/WidgetBudget.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetCardPerformance.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetCurrentMonth.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetItemCard.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetLastMonth.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetMtCredit.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetMyChallenge.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetUpcomingExpenses.tsx
  app/(home)/(default-home)/_components/widget-item/index.ts
  app/(home)/(default-home)/_loading.tsx
  app/(home)/(default-home)/context/OpenWalletProvider.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/(default-home)/page.tsx
  app/(home)/create-bucket/_components/BucketBottomSheet.tsx
  app/(home)/create-bucket/layout.tsx
  app/(home)/create-bucket/page.tsx
  app/(home)/edit-widget/_components/DragContainer.tsx
  app/(home)/edit-widget/_components/DragOverWidget.tsx
  app/(home)/edit-widget/_components/FixedBottom.tsx
  app/(home)/edit-widget/_components/IsEditWidgetItem.tsx
  app/(home)/edit-widget/_components/LoadingGrid.tsx
  app/(home)/edit-widget/_components/TopContents.tsx
  app/(home)/edit-widget/_components/TransitonContainer.tsx
  app/(home)/edit-widget/hooks/useDrag.ts
  app/(home)/edit-widget/hooks/useInsertAndDelete.ts
  app/(home)/edit-widget/layout.tsx
  app/(home)/edit-widget/page.tsx
  app/asset-management/_components/NetWorthSection.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/my-page/_components/Exam.tsx
  app/my-page/page.tsx
  components/header/IsBackHeader.tsx
  components/ui/IconButton.tsx
  hooks/useTotalWidth.ts
  hooks/useWindowResize.ts
  public/icons/home/three-dot.svg
  public/images/home/bucket-default.webp
  styles/style.css
Labels: chore, feat

#115 feat: 버킷 생성 페이지
  app/(home)/(default-home)/_components/BucketListCard.tsx
  app/(home)/(default-home)/_components/DefaultBucketListCard.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListCard.tsx
  app/(home)/(default-home)/_components/bucket-challenge/ListHeader.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/bucket-detail/_components/BucketBottomSheet.tsx
  app/(home)/bucket-detail/layout.tsx
  app/(home)/bucket-detail/page.tsx
  app/(home)/edit-widget/page.tsx
  app/asset-management/layout.tsx
  app/create-bucket/_components/BubbleText.tsx
  app/create-bucket/_components/BucketFlowHeader.tsx
  app/create-bucket/_components/BucketStepForm.tsx
  app/create-bucket/_components/InputCard.tsx
  app/create-bucket/_components/NextButton.tsx
  app/create-bucket/_components/PorkoImage.tsx
  app/create-bucket/_components/step/StepFour.tsx
  app/create-bucket/_components/step/StepOne.tsx
  app/create-bucket/_components/step/StepTwo.tsx
  app/create-bucket/_components/step/index.ts
  app/create-bucket/createBucketConfig.ts
  app/create-bucket/layout.tsx
  app/create-bucket/page.tsx
  app/layout.tsx
  components/Icon.tsx
  components/ui/Input.tsx
  hooks/useIsMounted.ts
  hooks/useWindowResize.ts
  middleware.ts
  public/images/create-bucket/bg.webp
  public/images/create-bucket/bubble.webp
  public/images/create-bucket/flow-1.png
  public/images/create-bucket/flow-2.png
  public/images/create-bucket/flow-3.png
  public/images/create-bucket/flow-4.png
  public/images/create-bucket/상품 고르는 포코.png
  public/images/home/bucket_img_step1.svg
  public/images/home/bucket_img_stpe3.svg
  public/images/home/bucket_img_stpe3.webp
  tailwind.config.ts
  types/svgComponentProps.ts
Labels: feat

#116 feat: budget calendar layout component
  app/budget-calendar/_components/common/Title.tsx
  app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
  app/budget-calendar/_components/look-alone/ExpensListBox.tsx
  app/budget-calendar/_components/look-alone/ExpensSummary.tsx
  app/budget-calendar/_components/look-alone/ExpenseItem.tsx
  app/budget-calendar/_components/look-together/ConsumptionWeather.tsx
  app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
  app/budget-calendar/_components/look-together/RegretSpending.tsx
  app/budget-calendar/_components/look-together/SharedCalendar.tsx
  app/budget-calendar/_components/look-together/SharedMembers.tsx
  types/budgetCalendarType.ts
  utils/dateUtils.ts
Labels: feat

#121 feat: 버킷리스 생성플로우
  app/(home)/(default-home)/_components/BucketListCard.tsx
  app/(home)/(default-home)/_components/HomeWidgetSection.tsx
  app/(home)/(default-home)/layout.tsx
  app/(home)/bucket-detail/_components/DetailHeader.tsx
  app/(home)/bucket-detail/layout.tsx
  app/auth/signup/layout.tsx
  app/create-bucket/_components/BucketFlowHeader.tsx
  app/create-bucket/_components/BucketStepForm.tsx
  app/create-bucket/_components/InputCard.tsx
  app/create-bucket/_components/NextButton.tsx
  app/create-bucket/_components/step/StepFour.tsx
  app/create-bucket/_components/step/StepOne.tsx
  app/create-bucket/_components/step/StepTwo.tsx
  app/create-bucket/createBucketConfig.ts
  app/create-bucket/layout.tsx
  app/create-bucket/page.tsx
  app/create-bucket/util.ts
  app/globals.css
  components/BottomSheet.tsx
  components/header/DefaultHeader.tsx
  components/ui/Input.tsx
  middleware.ts
  tailwind.config.ts
Labels: feat

#124 feat: 버킷 생성 플로우 작성
  app/(home)/bucket-detail/layout.tsx
  app/(home)/edit-widget/layout.tsx
  app/asset-management/_components/UpcomingScheduleSection.tsx
  app/create-bucket/_components/BubbleText.tsx
  app/create-bucket/_components/BucketFlowHeader.tsx
  app/create-bucket/_components/BucketStepForm.tsx
  app/create-bucket/_components/NextButton.tsx
  app/create-bucket/_components/PorkoImage.tsx
  app/create-bucket/_components/step/StepFour.tsx
  app/create-bucket/_components/step/StepOne.tsx
  app/create-bucket/_components/step/StepThree.tsx
  app/create-bucket/_components/step/StepTwo.tsx
  app/create-bucket/_components/step/index.ts
  app/create-bucket/createBucketConfig.ts
  app/create-bucket/data.ts
  app/create-bucket/layout.tsx
  app/create-bucket/page.tsx
  app/create-bucket/result/page.tsx
  app/create-bucket/util.ts
  components/TransitonContainer.tsx
  components/ui/Input.tsx
  hooks/useWindowResize.ts
  next.config.mjs
  public/images/asset-page/kb-card.svg
  public/images/asset-page/kb-card.webp
  public/images/asset-page/shinhan-card.svg
  public/images/asset-page/shinhan-card.webp
  public/images/create-bucket/flow-1.png
  public/images/create-bucket/flow-1.svg
  public/images/create-bucket/flow-2.png
  public/images/create-bucket/flow-2.webp
  public/images/create-bucket/flow-3.png
  public/images/create-bucket/flow-3.webp
  public/images/create-bucket/flow-4.png
  public/images/create-bucket/flow-4.webp
  public/images/create-bucket/flow-5.svg
  public/images/create-bucket/상품 고르는 포코.png
  utils/dateUtils.ts
  utils/deleteComma.ts
  utils/imageLoader.ts
Labels: feat

#128 feat: 홈 위젯 카드 구현
  app/(home)/(default-home)/_components/BucketListCard.tsx
  app/(home)/(default-home)/_components/DefaultBucketListCard.tsx
  app/(home)/(default-home)/_components/HomeTopBannerCard.tsx
  app/(home)/(default-home)/_components/HomeWidgetSection.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetBudget.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetCardPerformance.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetCurrentMonth.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetItemCard.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetLastMonth.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetMtCredit.tsx
  app/(home)/(default-home)/_components/widget-item/WidgetUpcomingExpenses.tsx
  app/(home)/(default-home)/page.tsx
  app/(home)/bucket-detail/layout.tsx
  app/auth/signup/(step-1)/page.tsx
  app/auth/signup/_components/SignupFormProvider.tsx
  app/auth/signup/step-2/page.tsx
  app/auth/signup/step-3/page.tsx
  app/create-bucket/_components/NextButton.tsx
  app/create-bucket/_components/step/StepFour.tsx
  components/DoughnutChart.tsx
  components/Icon.tsx
  hooks/useOnloadImage.ts
  package.json
  public/icons/categories/non-background/Layer_11.svg
  public/icons/categories/non-background/card.svg
  public/icons/categories/non-background/netflix.svg
  yarn.lock
Labels: feat, refactor
